---
apiVersion: v1
kind: Service
metadata:
  name: blue-cluster-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: simple-webpage
    #release: '${parameters.release}'
    release: 'v2'
